### ISSUE TITLE
support for debian conf files?

### ISSUE THREAD

**Issue by bedge** [gesellix/gradle-debian-plugin#10]
I don't see any info on this, so not sure of this is missing or not.

Does this plugin allow one to mark files as debian conf files [1]? 

Is so, how?

[1] https://wiki.debian.org/ConfigPackages see conffiles

**Comment by bedge** [comment]
Just curious if there's an interim hack one can use in the meantime?

**Comment by gesellix** [comment]
@bedge hey, sorry for the delay, I didn't have a chance to have a look at your question yet. But since the plugin relies on the JDeb library, I would suggest to check if JDeb supports debian conf files. I guess you already tried to just use debian conf files and it failed?!

**Comment by gesellix** [comment]
@bedge the new closures `conffile {}` and `conffileDir {}` should now allow you to add conf files. Usage is the same as with `file {}` and `dir {}`.

**Comment by gesellix** [comment]
P.S.: the plugin build needs to be fixed first, though, ... stay tuned!

**Comment by bedge** [comment]
Finally got back to this (after abandoning the nebula-plugins version because of its wonky maintainer script prefixing stuff).
conffileDir works beautifully, thanks!

**Comment by gesellix** [comment]
well, I actually thought about deprecating this plugin in favour of all the nebula-plugins, but if it does help you by being easier to use: great! :+1: :-)

**Comment by bedge** [comment]
Really? wow! I have to re-think this now. Sigh.
The nebula one forces some bolierplate headers onto all of the maintained scripts, so you end up only being able to handle the main cases. 
See: https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/119
Maybe it's the rpm support.

**Comment by gesellix** [comment]
well, after you still using this plugin, it's OK for me to continue maintaining it. it's not too much effort, I only thought the nebula plugins would be better. I don't think the Debian packaging concept to change too much.
so don't be afraid :-)

Am 21.08.2015 7:37 vorm. schrieb Bruce Edge <notifications@github.com>:Really? wow! I have to re-think this now. Sigh.
The nebula one forces some bolierplate headers onto all of the maintained scripts, so you end up only being able to handle the main cases. 
See: nebula-plugins/gradle-ospackage-plugin#119
Maybe it's the rpm support.
