### ISSUE TITLE
No [[artifactId]] or [[version]] repalcement in debian/*inst scripts.

### ISSUE THREAD

**Issue by bedge** [gesellix/gradle-debian-plugin#11]
Docs state that this uses the jdeb lib.
Using jdeb directly from maven does token replacement in *inst, and control files. 
This does not.
For example, I'd expect this line in postinst to get expanded with the actual artifactId:
```
chown -R nim_cas:nim_cas /opt//[[artifactId]]
```

**Comment by gesellix** [comment]
I'll update the jdeb dependency with the next release. Then I'll check whether the issue still persists.

**Comment by gesellix** [comment]
@bedge the updated release using jdeb 1.4 is available as "de.gesellix:gradle-debian-plugin:15", please give it a try and leave some feedback here. Thanks!

**Comment by thomwiggers** [comment]
I saw this happen in the `debian/control` file at least.

**Comment by gesellix** [comment]
@thomwiggers so it's still broken? (sorry for asking you to test it, I don't have a good local setup to actually test this use case)

**Comment by thomwiggers** [comment]
Nah, I meant I saw my `debian/control` go from `Name: [[packagename]]` to `Name: mypackagename` in the `.deb`.

**Comment by gesellix** [comment]
ah, ok, thanks @thomwiggers  :-)
So I would mark this as fixed.
@bedge please re-open this issue if it's not working for you!
