### ISSUE TITLE
Fails with messages about keysigning requested

### ISSUE THREAD

**Issue by thomwiggers** [gesellix/gradle-debian-plugin#12]
It appears that it is trying to use keysigning but the necessary settings can't be set.

**Comment by gesellix** [comment]
thanks for reporting!
do you have any example code to reproduce the error?

**Comment by thomwiggers** [comment]
I don't anymore, unfortunately, since I just deleted that from my build.gradle file... It pretty much followed the example in `README.md` though.

I was also using Gradle 2.5, if that matters.

**Comment by gesellix** [comment]
@thomwiggers an updated release is available as "de.gesellix:gradle-debian-plugin:15", please give it a try and leave some feedback here. Thanks!

**Comment by thomwiggers** [comment]
I think it now works, although I haven't tested this in full detail.

I now get this exception, but I'm unclear if this is my fault. I'm not really sure how the changelog generation is supposed to work.

```
:buildDeb (Thread[Daemon worker Thread 3,5,main]) started.
:buildDeb
Executing task ':buildDeb' (up-to-date check took 0.011 secs) due to:
  No history is available.
Creating debian package: /home/thom/git/irma_util/build/irma-util-1.0.deb
Building conffiles
Skipping 'conffiles' generation. No entries provided.
Creating changes file: /home/thom/git/irma_util/build/irma-util-1.0.changes
:buildDeb FAILED
:buildDeb (Thread[Daemon worker Thread 3,5,main]) completed. Took 0.049 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildDeb'.
> org.vafer.jdeb.PackagingException: Failed to create the Debian changes file /home/thom/git/irma_util/build/irma-util-1.0.changes```

**Comment by thomwiggers** [comment]
Also, I noticed that buildDeb doesn't depend on the `assemble` or `build` phases...

**Comment by gesellix** [comment]
@thomwiggers the buildDeb task should depend on `build`, but I had problems with making it dependent on `publishToMavenLocal`, which might cause issues now. Can you print the output of `./gradlew tasks --all`, please?

**Comment by thomwiggers** [comment]
well, `build` fails because I don't have all the dependencies for this project, but as you can see buildDeb was still attempted.

```
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Application tasks
-----------------
installApp - Installs the project as a JVM application along with libs and OS specific scripts. [jar]
    startScripts - Creates OS specific scripts to run the project as a JVM application.
run - Runs this project as a JVM application [classes]

Build tasks
-----------
assemble - Assembles the outputs of this project. [distTar, distZip, jar]
build - Assembles and tests this project. [assemble, check]
buildDeb - Build debian package
buildDependents - Assembles and tests this project and all projects that depend on it. [build]
buildNeeded - Assembles and tests this project and all projects it depends on. [build]
classes - Assembles classes 'main'.
    compileJava - Compiles Java source 'main:java'.
    processResources - Processes JVM resources 'main:resources'.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes. [classes]
testClasses - Assembles classes 'test'. [classes]
    compileTestJava - Compiles Java source 'test:java'.
    processTestResources - Processes JVM resources 'test:resources'.

Build Setup tasks
-----------------
init - Initializes a new Gradle build. [incubating]
wrapper - Generates Gradle wrapper files. [incubating]

Distribution tasks
------------------
assembleDist - Assembles the main distributions [distTar, distZip]
distTar - Bundles the project as a distribution. [jar]
    startScripts - Creates OS specific scripts to run the project as a JVM application.
distZip - Bundles the project as a distribution. [jar]
    startScripts - Creates OS specific scripts to run the project as a JVM application.
installDist - Installs the project as a distribution as-is. [jar]
    startScripts - Creates OS specific scripts to run the project as a JVM application.

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code. [classes]

Help tasks
----------
components - Displays the components produced by root project 'irma_util'. [incubating]
dependencies - Displays all dependencies declared in root project 'irma_util'.
dependencyInsight - Displays the insight into a specific dependency in root project 'irma_util'.
help - Displays a help message.
model - Displays the configuration model of root project 'irma_util'. [incubating]
projects - Displays the sub-projects of root project 'irma_util'.
properties - Displays the properties of root project 'irma_util'.
tasks - Displays the tasks runnable from root project 'irma_util'.

Verification tasks
------------------
check - Runs all checks. [test]
test - Runs the unit tests. [classes, testClasses]

Other tasks
-----------
install - Installs the 'archives' artifacts into the local Maven repository. [distTar, distZip, jar]

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

BUILD SUCCESSFUL

Total time: 4.053 secs
```

**Comment by gesellix** [comment]
that's interesting - did you update the dependency? My output looks lik this:

```
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build tasks
-----------
assemble - Assembles the outputs of this project. [jar]
build - Assembles and tests this project. [assemble, check]
buildDeb - Build debian package [build, publishToMavenLocal]
buildDependents - Assembles and tests this project and all projects that depend on it. [build]
...
```

Do you have a MavenPublication declared in your build script and have you added its name to the `debian.publications = [...]` list? The task dependency of `buildDeb` to `build` will only be added, when there's a MavenPublication.

**Comment by thomwiggers** [comment]
Ah, that explains things. I have not added a publication, as I didn't
really know what to put there. I don't really have the time to test this
right now, so I assume that explains the problems.

If adding a publication also fixes the changelog issue, then I guess
this issue can be closed.

**Comment by gesellix** [comment]
Just take your time testing it with your setup. I have to admit that I currently don't have a good setup to test everything, so I would be glad if you'd also give the changelog issue a try. We can keep this issue item open until then -  no pressure from my side :-)

**Comment by thomwiggers** [comment]
Perhaps you could answer some of my questions about what I exactly need
for a changelog

**Comment by gesellix** [comment]
you can check the test resources, e.g. at `.../src/test/resources/packagename/debian/changelog`. The changelog needs to be in a certain format, with spaces and braces being quite important. You can find a detailed description at http://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog and a more comprehensive description at http://www.debian.org/doc/manuals/maint-guide/dreq.en.html#changelog
You'll see in my test resources, that some fields are declared using a template like syntax. See the first line with `...version=[[version]]...` where the `[[version]]` value will be replaced with the actual artificat version.

Does that help?

**Comment by gesellix** [comment]
P.S.: as you'll see when reading the `.../src/test/resources/packagename/debian/changelog` file: I myself had a hard time understanding the mechanics and left a hopefully useful info about the changelog file right inside it :-)

**Comment by thomwiggers** [comment]
Seems to be working fine! 

I'm not really sure how the publications is supposed to work, adding:
```
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
```
doesn't really do much at all. Especially since I need to extract everything from the `installDist` target.

**Comment by gesellix** [comment]
Using the publications isn't mandatory. My personal use case was to distribute a Java webapp via debian packages. Publishing Java webapps in Gradle works with publications, which allows to declaratively link artifacts to the debian plugin.
In case you don't need that mechanism, that's ok. Then you only need to manually add your artifacts to the debian package.

**Comment by gesellix** [comment]
I'll close the issue now, but if you have further questions, feel free to ask!
