### ISSUE TITLE
Changing war name from maven-publisher plugin

### ISSUE THREAD

**Issue by bedge** [gesellix/gradle-debian-plugin#14]
Not a bug, more of a question of convention.

I couldn't figure out how to change the name from "publications" using the maven-publish plugin:
```
apply plugin: 'maven-publish'
publishing {
	publications {
	  webapp(MavenPublication) {
			groupId 'com.nim.collections'
			artifactId 'appname'
			version appVersion
		from components.web  // .war
	  }
	}
}
```
The above always results in the package containing ./usr/share/appname/publications

Is there a preferred way use the publishing plugin and change the war filename?

I was able to do it using this, and bypassing the publishing plugin completely:
```
		file {
			name = war.archiveName.replace("war-${version}.war", "${buildDir}/libs/war-${version}.war")
			mapper { 
				fileMode = "755"
			}	
		}
```

But, I expect there's a preferred way to set the artifact name while still using the maven-publish plugin.

**Comment by gesellix** [comment]
similar to your workaround you might try this (I didn't try it myself, though):

```
war {
   ...
   archiveName = 'foo.war'
}
```

all options to modify the artifact name can be found there: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.War.html

does that help or would the debian plugin need a configuration option?

**Comment by gesellix** [comment]
@bedge did the suggestion help?
I'm closing the issue now but feel free to re-open or continue adding questions here.
