### ISSUE TITLE
Getting error "Received status code 403 from server: Forbidden" with v2022-07-28T23-23-00

### ISSUE THREAD

**Issue by itsthamarai** [gesellix/gradle-debian-plugin#53]
Hi - We are using this version "v2022-07-28T23-23-00" in our project, we are getting the error "Could not GET 'https://mvnrepository.com/artifact/de.gesellix/gradle-debian-plugin/org/apache/maven/maven-archiver/3.8.5/maven-archiver-3.8.5.pom'. Received status code 403 from server: Forbidden" for the last couple of days.

**Comment by gesellix** [comment]
Hey, can you share more details about your project configuration? The download path looks suprising to me, because the maven-archiver pom should not be a subdirectory of the gradle-debian-plugin.
I suppose your repository configuration might point to mvnrepository.com instead of something like [https://repo1.maven.org/maven2/](https://repo1.maven.org/maven2/).

**Comment by itsthamarai** [comment]
Sure. This is what we have in build.gradle. 

buildscript {
  repositories {
    maven {
     url "https://mvnrepository.com/artifact/de.gesellix/gradle-debian-plugin"
    }
    mavenCentral()
  }
  dependencies {
    classpath("de.gesellix:gradle-debian-plugin:2022-07-28T23-23-00")
  }
}
I hope this helps.

**Comment by gesellix** [comment]
So, the `url` should be changed. Please check the description at the plugin portal: https://plugins.gradle.org/plugin/de.gesellix.debian

For modern versions of Gradle your config should be replaced by:

```
plugins {
  id("de.gesellix.debian") version "2022-07-28T23-23-00"
}
```

**Comment by gesellix** [comment]
@itsthamarai did that help?

**Comment by itsthamarai** [comment]
No, it is still the same issue. Getting "Could not find org.apache.maven:maven-archiver:3.8.5.' error.

**Comment by gesellix** [comment]
Can you run the build including `--info --stacktrace` and post the complete error here? Please remove any sensitive details and credentials if they appear in the error message.
Also, please check again that both settings.gradle and build.gradle don't reference any hard coded url with `https://mvnrepository.com/`.

**Comment by itsthamarai** [comment]
A problem occurred configuring root project ' '.
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.apache.maven:maven-archiver:3.8.5.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/3.8.5/maven-archiver-3.8.5.pom
       - {INTERNAL REPO}
       - https://plugins.gradle.org/m2/org/apache/maven/maven-archiver/3.8.5/maven-archiver-3.8.5.pom
     Required by:
         project : > de.gesellix.debian:de.gesellix.debian.gradle.plugin:2022-07-28T23-23-00 > de.gesellix:gradle-debian-plugin:2022-07-28T23-23-00
   > Could not find org.apache.maven:maven-archiver:3.8.5.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/3.8.5/maven-archiver-3.8.5.pom
       - {INTERNAL REPO}
       - https://plugins.gradle.org/m2/org/apache/maven/maven-archiver/3.8.5/maven-archiver-3.8.5.pom
     Required by:
         project : > de.gesellix.debian:de.gesellix.debian.gradle.plugin:2022-07-28T23-23-00 > de.gesellix:gradle-debian-plugin:2022-07-28T23-23-00 > org.vafer:jdeb:1.10

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by gesellix** [comment]
Thanks, I finally found the reason and I'm going to release a fix this week.

**Comment by gesellix** [comment]
An updated plugin with the [dependency fix](https://github.com/gesellix/gradle-debian-plugin/pull/54) is now available:

```
plugins {
  id("de.gesellix.debian") version "2024-07-13T09-15-00"
}
```

**Comment by gesellix** [comment]
Thanks a lot for your patience! If anything still doesn't work, please leave a note here or create another issue.

**Comment by itsthamarai** [comment]
Thank you!! It works great now..
